### ISSUE TITLE
New store release

### ISSUE THREAD

**Issue by NomarCub** [7fffffff/linkgrabber#25]
The Chrome webstore says the extension was last updated in 2021, but there are recent changes in the repository.

Also, the store page does not link to this repo, so for all I know the author could be faked in either direction. You should put the link to the source in the description there, or there's a separate website field under Additional Information on other extensions in the store which could be used.

**Comment by 7fffffff** [comment]
I've added the repo URL to the extension description and submitted for review.

Right now, there's not really not much new functionality vs the released version. I want to add options to control the default state of the various toggles. If I can find the time to implement that, I will cut a new release.
